name: drift_table_to_model
description: Dart builder to generate model classes from drift table classes
version: 1.0.0
repository: https://github.com/idkwhodatis/drift_table_to_model

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.7.0
  glob: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.12
